name: Lint, Test, and Danger

on: pull_request

jobs:
  lint-test-danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_DECRAPIFIER }}
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn run lint:ci || touch FAIL_JOB

      - name: Test
        run: yarn run test:ci || touch FAIL_JOB

      - name: Setup Decrapifier user
        run: |
          git config user.email "decrapifier@govspend.com"
          git config user.name "Decrapifier"
          git config push.default upstream
          git checkout --track origin/${{github.head_ref}}

      - name: Run danger
        run: yarn run danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.PAT_DECRAPIFIER }}
